source 'https://github.com/CocoaPods/Specs.git'

target 'TOCScreenshot', :exclusive => true do
  pod "TOCScreenshot", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TOCScreenshot", :path => "../"

  
end
